const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 * 
 * ! Generated by React Native
 */
const config = {};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
